Update build-test-deploy.yml

diff --git a/.github/workflows/build-test-deploy.yml b/.github/workflows/build-test-deploy.yml
--- a/.github/workflows/build-test-deploy.yml
+++ b/.github/workflows/build-test-deploy.yml
@@ -9,11 +9,25 @@ jobs:
     steps: 
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
       - name: Verify repository content
-        run: ls -la # Provera da li je package.json prisutan
+        run: ls -la # Proverava sadržaj direktorijuma
+
       - name: Use Node.js
         uses: actions/setup-node@v4
         with:  
           node-version: '20.x'
-      - run: npm install
-      - run: npm run build
+
+      - name: Install dependencies
+        run: |
+          if [ -f package.json ]; then
+            npm install
+          else
+            echo "package.json not found!"
+            exit 1
+          fi
+
+      - name: Build project
+        run: npm run build
